name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-12, macos-11, windows-2022, windows-2019]
        elasticsearch-version: [8, 7]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.
        with:
          elasticsearch-version: ${{ matrix.elasticsearch-version }}
          plugins: |
            analysis-kuromoji
            analysis-smartcn
          config: |
            cluster.name: my-cluster
            http.port: 9201
      - run: curl -s localhost:9201
      - run: curl -s localhost:9201 | grep my-cluster
      - run: which elasticsearch
      - run: elasticsearch-plugin list
